backend:
  name: github
  repo: your-github-username/aesthetics-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "testimonials"
    label: "Testimonials"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Testimonial", name: "text", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "pricing"
    label: "Pricing"
    folder: "content"
    create: false
    slug: "pricing"
    fields:
      - label: "Services"
        name: "services"
        widget: "list"
        fields:
          - { label: "Service Name", name: "name", widget: "string" }
          - { label: "Price", name: "price", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
